# Generated by Django 3.0.5 on 2022-09-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'tags'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_name',
            field=models.CharField(max_length=20),
        ),
    ]
